version: '3'
services:
#  evaluator:
#    environment:
#      solution_parameters: |
#        {env: Duckietown-Lf-Lfv-Navv-Silent-v1}
#
#      launcher_parameters: |
#        challenge: LF
#        episodes: 7
#        steps_per_episode: 500
#        include_map: true
#
#        environment-constructor: Simulator
#
#        # passed to the environment
#        environment-parameters:
#          seed: 123 # random seed
#          map_name: loop_empty # loop_obstacles # loop_pedestrians
#          max_steps: 500001 # we don't want the gym to reset itself
#          domain_rand: 0
#          camera_width: 640
#          camera_height: 480
#          accept_start_angle_deg: 6 # start close to straight
#          full_transparency: true
#          distortion: true
#        # passed to the agent in the "misc" field
#        agent-info:
#          challenge: LF
#    build:
#      context: ./simulation
#    volumes:
#      - fifos:/fifos
#      - ./simulation:/project
  experiment_manager:
    environment:
      AIDONODE_ENCODING: cbor
      DTG_LOG_DIR: /logs
      experiment_manager_parameters: |
        challenge: LF
        episodes: 7
        steps_per_episode: 14
        min_nsteps: 1
    build:
      context: ./experiment_manager
    volumes:
      - ./logs:/logs
      - fifos:/fifos
      - /data/work/vmware-michela-shared/DT/dt-env/dt-env-developer/src/aido-protocols/src:/project/src/aido-protocols/src
      - /data/work/zupermind/env/zuper_json:/project/src/zuper-utils
#      - ./experiment_manager:/project
  simulator:
    build:
      context: ./simulator_only
    environment:
      AIDONODE_DATA_IN: /fifos/simulator-in
      AIDONODE_DATA_OUT: fifo:/fifos/simulator-out
      AIDONODE_META_IN:
      AIDONODE_META_OUT:
      AIDONODE_ENCODING: cbor
      launcher_parameters: |
        challenge: LF
        episodes: 7
        steps_per_episode: 500
        include_map: true

        environment-constructor: Simulator

        # passed to the environment
        environment-parameters:
          seed: 123 # random seed
          map_name: loop_empty # loop_obstacles # loop_pedestrians
          max_steps: 500001 # we don't want the gym to reset itself
          domain_rand: 0
          camera_width: 640
          camera_height: 480
          accept_start_angle_deg: 6 # start close to straight
          full_transparency: true
          distortion: true
    volumes:
      - fifos:/fifos
      - /data/work/vmware-michela-shared/DT/dt-env/dt-env-developer/src/aido-protocols/src:/project/src/aido-protocols/src
      - /data/work/zupermind/env/zuper_json:/project/src/zuper-utils
      - ./simulator_only:/project
      - /data/work/vmware-michela-shared/DT/dt-env/dt-env-developer/src/simulators/gym-duckietown:/gym-duckietown
  solution:
    image: duckietown/aidonode-random_agent:v4-devel3
    environment:
      AIDONODE_DATA_IN: /fifos/agent-in
      AIDONODE_DATA_OUT: fifo:/fifos/agent-out
      AIDONODE_META_IN:
      AIDONODE_META_OUT:
      AIDONODE_ENCODING: cbor
    volumes:
      - fifos:/fifos
      - /data/work/vmware-michela-shared/DT/dt-env/dt-env-developer/src/aido-protocols/src:/project/src/aido-protocols/src
      - /data/work/zupermind/env/zuper_json:/project/src/zuper-utils
      - /data/work/vmware-michela-shared/DT/dt-env/dt-env-developer/src/aido-protocols/minimal-nodes-stubs/random_agent:/project
volumes:
  fifos:
